my_trino_profile:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: trino
      host: trino
      port: 8080
      database: iceberg
      schema: default
      threads: 1
