# Spark (with Iceberg support)
# Trino (querying Iceberg tables)
# MinIO (S3-compatible object storage)
# ClickHouse
# JupyterLab
# Ready for Spring Boot to connect via JDBC / REST

# Service	    URL
# MinIO Console	http://localhost:9001
# Spark UI	    http://localhost:8080
# Trino UI	    http://localhost:8081
# ClickHouse	http://localhost:8123
# JupyterLab	http://localhost:8888

version: "3.9"

services:

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  spark:
    image: apache/spark:3.4.1
    container_name: spark
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      SPARK_NO_DAEMONIZE: "true"

  spark-worker:
    image: apache/spark:3.4.1
    container_name: spark-worker
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark:7077
    depends_on:
      - spark
    environment:
      SPARK_NO_DAEMONIZE: "true"

  trino:
    image: trinodb/trino:435
    container_name: trino
    ports:
      - "8081:8080"

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9002:9000"

  jupyter:
    image: jupyter/pyspark-notebook:spark-3.4.1
    container_name: jupyter
    ports:
      - "8888:8888"
    depends_on:
      - spark

volumes:
  minio-data:
