#Full ETL pipeline stack
#S3 storage via MinIO
#Metadata via Hive Metastore
#Iceberg tables
#SQL querying via Trino
#ETL compute via Spark
#Ingestion via NiFi
#Scheduling via Airflow

#This is a complete Snowflake-like Apache-based ETL lakehouse, runnable locally with Podman.

version: "3.9"

services:

  #################################################
  # MinIO
  #################################################
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data


  #################################################
  # PostgreSQL
  #################################################
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hivepass
      POSTGRES_DB: metastore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  #################################################
  # Hive Metastore
  #################################################
  hive-metastore:
    image: apache/hive:3.1.3
    depends_on:
      - postgres
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      HIVE_METASTORE_DB_HOST: postgres
      HIVE_METASTORE_DB_NAME: metastore
      HIVE_METASTORE_DB_USER: hive
      HIVE_METASTORE_DB_PASS: hivepass
    ports:
      - "9083:9083"


  #################################################
  # NiFi
  #################################################
  nifi:
    image: apache/nifi:1.23.2
    environment:
      NIFI_WEB_HTTP_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - nifi_data:/opt/nifi/nifi-current/data


  #################################################
  # Airflow
  #################################################
  airflow:
    image: apache/airflow:2.9.2-python3.10
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://hive:hivepass@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    ports:
      - "8081:8080"
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com &&
      airflow webserver &
      airflow scheduler
      "
    volumes:
      - ./dags:/opt/airflow/dags


  #################################################
  # Spark – corrected image tag
  #################################################
  spark:
    image: apache/spark:3.5.1
    container_name: spark
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "4040:4040"


  #################################################
  # Trino
  #################################################
  trino:
    image: trinodb/trino:443
    ports:
      - "8082:8080"
    volumes:
      - ./trino:/etc/trino
    depends_on:
      - hive-metastore
      - minio


volumes:
  postgres_data:
  minio_data:
  nifi_data:
